$(function(){
$(".imgzz").hover(function(){
    $(".maskzz").css("display","block");
   },function(){
     $(".maskzz").css("display","none");
   })
   $(".imgzy").hover(function(){
    $(".maskzy").css("display","block");
   },function(){
     $(".maskzy").css("display","none");
   })
   $(".imgmz").hover(function(){
    $(".maskmz").css("display","block");
   },function(){
     $(".maskmz").css("display","none");
   })
   $(".imggz").hover(function(){
    $(".maskgz").css("display","block");
   },function(){
     $(".maskgz").css("display","none");
   })
   $(".imgxz").hover(function(){
    $(".maskxz").css("display","block");
   },function(){
     $(".maskxz").css("display","none");
   })
   $(".imglz").hover(function(){
    $(".masklz").css("display","block");
   },function(){
     $(".masklz").css("display","none");
   })
   $(".imgwx").hover(function(){
    $(".maskwx").css("display","block");
   },function(){
     $(".maskwx").css("display","none");
   })
   $(".imgey").hover(function(){
    $(".maskey").css("display","block");
   },function(){
     $(".maskey").css("display","none");
   })
   $("#flie1").mouseover(function(){
		$("#onemout").css({"display":"block",
						"border-radius":"20px",
						"transition":".5s"})
	})
	$("#flie2").mouseover(function(){
		$("#twomout").css({"display":"block",
						"border-radius":"20px",
						"transition":".5s"})
	})
	$("#flie3").mouseover(function(){
		$("#threemout").css({"display":"block",
						"border-radius":"20px",
						"transition":".5s"})
	})
	$("#flie4").mouseover(function(){
		$("#fourmout").css({"display":"block",
						"border-radius":"20px",
						"transition":".5s"})
	})
	$("#flie5").mouseover(function(){
		$("#fivemout").css({"display":"block",
						"border-radius":"20px",
						"transition":".5s"})
	})
	$("#flie6").mouseover(function(){
		$("#sixmout").css({"display":"block",
						"border-radius":"20px",
						"transition":".5s"})
	})
	$(".rean").mouseout(function(){
		$(".eio").css({"display":"none",
						})
	})
})